pipeline {
    agent any

    environment {
      IMAGE_NAME = 'peerawitp/jenkins-lab'
      DOCKERFILE = './docker/Dockerfile'
    }

    stages {
      stage('Build and push docker image') {
        steps {
          script {
              def dockerImage = docker.build("${IMAGE_NAME}:${env.BUILD_ID}", "-f ${DOCKERFILE} .")
              docker.withRegistry('https://docker.io', 'docker-hub-peerawitp') {
                dockerImage.push()
                dockerImage.push('latest')
              }
          }
        }
      }
    }
}
