pipeline {
    agent any

    environment {
      IMAGE_NAME = 'peerawitp/jenkins-lab'
    }

    stages {
      def dockerfile = './docker/Dockerfile'
      stage('Build and push docker image') {
        steps {
          script {
              docker.withRegistry('https://hub.docker.com', 'docker-hub-peerawitp') {
                def dockerImage = docker.build("${IMAGE_NAME}:${env.BUILD_ID}", "-f ${dockerfile}")
                dockerImage.push()
                dockerImage.push('latest')
              }
          }
        }
      }
    }
}
